import SortingAdversary.Strategy
import SortingAdversary.Knowledge
import SortingAdversary.Potential
import SortingAdversary.PotentialAdversary
import SortingAdversary.AsymptoticStatement
import SortingAdversary.StrengthenedCurvature.ApproximateRule
import SortingAdversary.StrengthenedCurvature.EfficientRule

/-!
# Audit surface

The declarations printed here are the small semantic interface a reviewer
should inspect before relying on the kernel-checked proof beneath it.
-/

#print SortingAdversary.Query
#print SortingAdversary.Ranking
#print SortingAdversary.DecisionTree
#print SortingAdversary.DecisionTree.Correct
#print SortingAdversary.AdversaryCertificate
#print SortingAdversary.lower_bound_of_adversary_certificate
#print SortingAdversary.PotentialCertificate
#print SortingAdversary.PotentialAdversaryCertificate
#print SortingAdversary.PotentialCertificate.target_le_length_mul
#print SortingAdversary.HasLeadingConstant
#print SortingAdversary.strengthenedCurvatureConstant
#check SortingAdversary.strengthenedCurvatureConstant_lt_eighteen_twentyfive
#check SortingAdversary.seven_one_five_five_ten_thousandths_lt_strengthenedCurvatureConstant
#check SortingAdversary.sixty_nine_hundredths_lt_strengthenedCurvatureConstant
#print SortingAdversary.StrengthenedCurvature.PotentialRule
#print SortingAdversary.StrengthenedCurvature.InformativePotentialRule
#print SortingAdversary.StrengthenedCurvature.CertifiedRuleFamily
#check SortingAdversary.StrengthenedCurvature.CertifiedRuleFamily.target
#check SortingAdversary.StrengthenedCurvature.efficientInformativeRule
#check SortingAdversary.StrengthenedCurvature.efficientCertifiedRuleFamily
#check SortingAdversary.StrengthenedCurvature.efficient_curvature_adversary
#check SortingAdversary.StrengthenedCurvature.approximateChildAnswer_le_min_add
#check SortingAdversary.StrengthenedCurvature.projection_curvature_upper
#check SortingAdversary.StrengthenedCurvature.hasDerivAt_scaledLogDetFirst_projection
#check SortingAdversary.StrengthenedCurvature.doublySubstochastic_quadratic_lower
#check SortingAdversary.StrengthenedCurvature.RationalInterval.log_rational_mem
#check SortingAdversary.StrengthenedCurvature.exists_volumetricCenter
#check SortingAdversary.StrengthenedCurvature.IsVolumetricCenter.leverage_balance
#check SortingAdversary.StrengthenedCurvature.electricalMotion_energy_one
#check SortingAdversary.StrengthenedCurvature.strengthened_certificate_check
#check SortingAdversary.StrengthenedCurvature.strengthened_segment_certificate
#check SortingAdversary.StrengthenedCurvature.min_trial_scaledLogDet_le_scalarEnvelope

#print axioms SortingAdversary.lower_bound_of_adversary_certificate
#print axioms SortingAdversary.PotentialCertificate.target_le_length_mul
#print axioms SortingAdversary.PotentialAdversaryCertificate.lower_bound
#print axioms SortingAdversary.StrengthenedCurvature.PotentialRule.comparisons_lower_bound
#print axioms SortingAdversary.StrengthenedCurvature.barrierRows_slack_pos
#print axioms SortingAdversary.StrengthenedCurvature.doublySubstochastic_quadratic_lower
#print axioms SortingAdversary.StrengthenedCurvature.RationalInterval.log_rational_mem
#print axioms SortingAdversary.StrengthenedCurvature.exists_volumetricCenter
#print axioms SortingAdversary.StrengthenedCurvature.IsVolumetricCenter.leverage_balance
#print axioms SortingAdversary.StrengthenedCurvature.electricalMotion_energy_one
#print axioms SortingAdversary.strengthenedCurvatureConstant_lt_eighteen_twentyfive
#print axioms SortingAdversary.seven_one_five_five_ten_thousandths_lt_strengthenedCurvatureConstant
#print axioms SortingAdversary.sixty_nine_hundredths_lt_strengthenedCurvatureConstant
#print axioms SortingAdversary.StrengthenedCurvature.CertifiedRuleFamily.target
#print axioms SortingAdversary.StrengthenedCurvature.strengthened_certificate_check
#print axioms SortingAdversary.StrengthenedCurvature.strengthened_segment_certificate
#print axioms SortingAdversary.StrengthenedCurvature.efficient_curvature_adversary
#print axioms SortingAdversary.StrengthenedCurvature.approximateChildAnswer_le_min_add
#print axioms SortingAdversary.StrengthenedCurvature.projection_curvature_upper
#print axioms SortingAdversary.StrengthenedCurvature.hasDerivAt_scaledLogDetFirst_projection
