import SortingAdversary.Basic

/-!
# Relation-valued knowledge states

This file connects adversarial bookkeeping to actual rankings without assuming
that a custom state representation is itself a standard mathlib partial order.
The closure operation is defined explicitly and its semantic soundness is
proved by induction.
-/

namespace SortingAdversary

/-- The ordering information currently asserted by an adversary. -/
structure Knowledge (n : ℕ) where
  rel : Item n → Item n → Prop

namespace Knowledge

/-- A concrete ranking realizes every asserted relation. -/
def Realizes (π : Ranking n) (K : Knowledge n) : Prop :=
  ∀ ⦃x y : Item n⦄, K.rel x y → π x < π y

/-- A knowledge state is semantically consistent when some ranking realizes it. -/
def Consistent (K : Knowledge n) : Prop :=
  ∃ π : Ranking n, K.Realizes π

/-- The empty initial knowledge state. -/
def empty (n : ℕ) : Knowledge n := ⟨fun _ _ => False⟩

@[simp] theorem realizes_empty (π : Ranking n) : (empty n).Realizes π := by
  intro x y h
  exact h.elim

/-- Transitive closure after adjoining one answered comparison. -/
inductive AddAnswerClosure (K : Knowledge n) (o : Observation n) : Item n → Item n → Prop
  | old {x y} : K.rel x y → AddAnswerClosure K o x y
  | answerLess : o.answer = .less → AddAnswerClosure K o o.query.left o.query.right
  | answerGreater : o.answer = .greater → AddAnswerClosure K o o.query.right o.query.left
  | trans {x y z} : AddAnswerClosure K o x y → AddAnswerClosure K o y z →
      AddAnswerClosure K o x z

/-- Update knowledge by adjoining an answer and taking transitive closure. -/
def addAnswer (K : Knowledge n) (o : Observation n) : Knowledge n :=
  ⟨AddAnswerClosure K o⟩

/-- The explicit closure update says nothing beyond the old information, the
new answered comparison, and transitivity. -/
theorem realizes_addAnswer (π : Ranking n) (K : Knowledge n) (o : Observation n)
    (hK : K.Realizes π) (ho : o.Holds π) : (K.addAnswer o).Realizes π := by
  intro x y hxy
  induction hxy with
  | old h => exact hK h
  | answerLess h =>
      simpa [Observation.Holds, h] using ho
  | answerGreater h =>
      simpa [Observation.Holds, h] using ho
  | trans h₁ h₂ ih₁ ih₂ =>
      exact lt_trans ih₁ ih₂

/-- A single concrete realizer that also satisfies the new answer witnesses
consistency of the updated state. -/
theorem consistent_addAnswer_of_realizer (K : Knowledge n) (o : Observation n)
    (π : Ranking n) (hK : K.Realizes π) (ho : o.Holds π) :
    (K.addAnswer o).Consistent := by
  exact ⟨π, realizes_addAnswer π K o hK ho⟩

/-- Updating is consistent exactly when we can exhibit an old realizer that
also satisfies the chosen answer.  The forward implication needed by an
adversary is exposed as a small, auditable constructor. -/
theorem consistent_addAnswer (K : Knowledge n) (o : Observation n)
    (h : ∃ π : Ranking n, K.Realizes π ∧ o.Holds π) :
    (K.addAnswer o).Consistent := by
  obtain ⟨π, hK, ho⟩ := h
  exact consistent_addAnswer_of_realizer K o π hK ho

/-- Build the explicit closed knowledge relation generated by a transcript. -/
def ofHistory : History n → Knowledge n
  | [] => empty n
  | o :: h => (ofHistory h).addAnswer o

/-- Every ranking compatible with a transcript realizes its generated closed
knowledge relation. -/
theorem realizes_ofHistory (π : Ranking n) :
    ∀ h : History n, Compatible π h → (ofHistory h).Realizes π
  | [], _ => realizes_empty π
  | o :: h, hcompat => by
      have hparts := (compatible_cons π o h).1 hcompat
      exact realizes_addAnswer π (ofHistory h) o
        (realizes_ofHistory π h hparts.2) hparts.1

/-- A compatible transcript therefore has a semantically consistent generated
knowledge state. -/
theorem consistent_ofHistory (h : History n)
    (π : Ranking n) (hcompat : Compatible π h) : (ofHistory h).Consistent := by
  exact ⟨π, realizes_ofHistory π h hcompat⟩

end Knowledge
end SortingAdversary
